### ISSUE TITLE
New suggestion

### ISSUE THREAD

**Issue by DeathGOD7** [DeathGOD7/unexpectedspawn-paper#13]
![image](https://user-images.githubusercontent.com/36422471/130211767-bbf5b564-e1af-4dab-84ec-db52238be0c1.png)
![image](https://user-images.githubusercontent.com/36422471/130211802-3db371d6-e96b-4c73-9f39-18cf5f3ea81e.png)

Some suggestions by a friend.

**Comment by RexSE7EN** [comment]
- Fail radius added.

~~Now to respect world guard, towny, and other grief prevention areas.~~ (in 0.3.2)
