### ISSUE TITLE
Essentials home compatibility

### ISSUE THREAD

**Issue by twixi** [DeathGOD7/unexpectedspawn-paper#14]
I have a problem: in a normal world everything is fine, but when I'm in another world, using the /home command I go to the normal world, but in a random position! - Me need to repeat /home to be at bed again!
my config:
https://pastebin.com/UdeJAsWq

**Comment by RexSE7EN** [comment]
First of all, sorry for the late response as I don't have much time available for this project as I am busy with work. But I will maintain it and keep updating in my free time. And please use https://paste.gg or https://pastebin.com or any paste sites. As the direct input is confusing and is not good for us to debug.

And also send the logs when making ``debug: true`` in config.

2nd of all, Essentials uses either bed respawns method for home or teleport. Haven't looked in their code. If its bed respawns then "bed-respawn-enabled: false" needs to be true in your current world (the one you are coming or traveling back from like another dimension world). Just having it in global variable won't be enough as the custom per world config overrides it. Maybe blacklist doesn't work when you have specified them in custom override worlds or it checks the one you are going. (AFAIK I didn't have any trouble having them and doing blacklist in 1.16.5).

PS : Try removing the custom overrides and see if it fixes it. ( ``worlds: []`` )

Also, you have DIM7 or DIM-1 or DIM1...do you have custom dimensions? Maybe other mods? If it's nether or endcity then you should write the exact name when your other world is stored.

You can safely do random respawn in other dimensions also as you can specify where players will respawn. And have them respect bed respawn if you are having trouble with /home from other dimensions.

**Final Note :**
```
I have a problem: in a normal world everything is fine, but when I'm in another world, using the /home command I go to the normal world, but in a random position! - Me need to repeat /home to be at bed again!
```
You said the normal world is fine but in another world, it gives that bug right? Please specify the world type or names. If it's end city or nether then when coming back from end portal or nether portal the game uses half-dead mechanics. It's kinda like killing and sending you but with all your items and xp. (I had fixed the end portal and main island portals issue which used to bug your respawn and when logging back it will instantly kill you from the high place and your items being gone in the portal)

If it's really essential conflicting with respawn mechanics (by doing teleport and not respawn with bed) then will try to see what I can do as I have to know about their API to access if users have set home.

**Comment by twixi** [comment]
Normal world - "/home" and "/suicide" all ok
World "DIM7" (twilight forest) - "/suicide" is ok (spawn to home in normal world), "/home" - spawn on normal world, but random coordinates... (not spawn on bed)
The End "DIM1"  - "/suicide" is ok (spawn to home in normal world), "/home" - spawn on normal world, but random coordinates... (not spawn on bed)(need retype /home command)
Nether "DIM-1" - "/suicide" is ok (spawn to home in normal world), "/home" - spawn on normal world, but random coordinates... (not spawn on bed) (need retype /home command)


logs - [Essentials] Could not find bed spawn, forcing respawn event.

essentials (version: Pre2.14.1.3) - https://pastebin.com/6pbxkZnS
uns (version: 0.3.0+hotfix.1)- https://pastebin.com/sqvA6v59
permissinsex - https://pastebin.com/bZea3KsC

**Comment by RexSE7EN** [comment]
> Normal world - "/home" and "/suicide" all ok World "DIM7" (twilight forest) - "/suicide" is ok (spawn to home in normal world), "/home" - spawn on normal world, but random coordinates... (not spawn on bed) The End "DIM1" as in DIM7 Nether "DIM-1" as in DIM7
> 
> essentials (version: Pre2.14.1.3) - https://pastebin.com/6pbxkZnS uns (version: 0.3.0+hotfix.1)- https://pastebin.com/sqvA6v59 permissinsex - https://pastebin.com/bZea3KsC

So DIM7 is only having trouble, right? or both Nether and End also?
And how are you managing these worlds? Multiverse? If yes what version?

I believe there are settings in the essential plugin to determine which takes priority. This one :
```
# Set this to lowest, if you want Multiverse to handle the respawning.
# Set this to high, if you want EssentialsSpawn to handle the respawning.
# Set this to highest, if you want to force EssentialsSpawn to handle the respawning.
respawn-listener-priority: high
 
# Коли користувачі вмирають, вони повинні відроджуватися в своєму першому будинку або ліжка, замість спавнпоінта?
respawn-at-home: true
```
Also, try setting to lowest and see what happens.

And provide a full /pl list.

**Comment by twixi** [comment]
change `respawn-listener-priority: lowest`

Normal world - "/home" and "/suicide" all ok
World "DIM7" (twilight forest) - "/suicide"  - spawn on at portal in DIM7 , "/home" - spawn on normal world, but random coordinates... (not spawn on bed)
The End "DIM1" - "/suicide" is ok (spawn to home in normal world), "/home" - spawn on normal world, but random coordinates... (not spawn on bed)(need retype /home command)
Nether "DIM-1" - "/suicide" is ok (spawn to home in normal world), "/home" - spawn on normal world, but random coordinates... (not spawn on bed) (need retype /home command)

logs - [Essentials] Could not find bed spawn, forcing respawn event.

> And how are you managing these worlds? Multiverse? If yes what version?
Default The End, Nether and mod Twilight Forest

pl: WorldEdit, Essentials, WorldBorder, WorldGuard, ProtocolLib, UnexpectedSpawn, PermissionsEx

**Comment by RexSE7EN** [comment]
> change `respawn-listener-priority: lowest`
> 
> Normal world - "/home" and "/suicide" all ok World "DIM7" (twilight forest) - "/suicide" - spawn on at portal in DIM7 , "/home" - spawn on normal world, but random coordinates... (not spawn on bed) The End "DIM1" - "/suicide" is ok (spawn to home in normal world), "/home" - spawn on normal world, but random coordinates... (not spawn on bed)(need retype /home command) Nether "DIM-1" - "/suicide" is ok (spawn to home in normal world), "/home" - spawn on normal world, but random coordinates... (not spawn on bed) (need retype /home command)
> 
> logs - [Essentials] Could not find bed spawn, forcing respawn event.
> 
> > And how are you managing these worlds? Multiverse? If yes what version?
> > Default The End, Nether and mod Twilight Forest
> 
> pl: WorldEdit, Essentials, WorldBorder, WorldGuard, ProtocolLib, UnexpectedSpawn, PermissionsEx

Well as your log says `` [Essentials] Could not find bed spawn, forcing respawn event. ``
Did you by chance add those 3 other dimensions manually? Have you linked them? Are they a nether type world or end type? Especially Twilight Forest. And try linking them by naming them like world. world_nether, world_the_end, and others.

You can also give try to Multiverse-Core and Multiverse-Nether if you wanna link worlds.

**Comment by RexSE7EN** [comment]
**Update**: I have tested Unexpected Spawn 0.3.1-beta with Essential 2.19.2 in Minecraft 1.14.4 and everything seems to work.
As it seems /home is just normal teleport.

Tested Worlds: world (default), world_nether (default), world_the_end (default) [All worlds were auto-generated at startup.)
Config: Both plugins made the default config file.

Did run the test from both nether and end with /home and it was working. Seems the world link is the issue with you. Not our plugin nor essential plugin is at fault here.
So please either link the worlds with multiverse if custom dimensions.

I think the issues here are resolved. Can I close this issue?

\- [SE7EN] Death GOD 7

**Comment by RexSE7EN** [comment]
Closing the issue as its not related to our plugin and author is inactive.
