### ISSUE TITLE
Saving spawn point in first-join mode for player

### ISSUE THREAD

**Issue by DjArt** [DeathGOD7/unexpectedspawn-paper#16]
I want to remake [#1](https://github.com/Shivelight/unexpectedspawn-paper/pull/1) pull with fixes.
But, I have several questions.

1. Looks like first-join, first-join with saving and always-on-join modes are incompatible together. Should I edit configuration file logic to make mode selection looks like: `randomization-mode: first-join` , `randomization-mode: first-join-fixed`, `randomization-mode: always-on-join`?
2. Where you suggest to save coordinates? Should it be a additional config file or player .dat file or something else?

I would be glad for any other help.

**Comment by RexSE7EN** [comment]
First of all, sorry for the late response.

But this plugin doesn't save data/coordinates when players first join the server. They are randomly thrown in overworld based on the config file. And always-on-join and first-join are triggered on different conditions.

```java

        if ((!event.getPlayer().hasPlayedBefore() && plugin.config.getConfig().getBoolean(useCustomOnFirstJoin + "random-respawn.on-first-join")) ||
          plugin.config.getConfig().getBoolean(useCustomAlwaysOnJoin + "random-respawn.always-on-join")) {

          Location joinLocation = getRandomSpawnLocation(joinWorld);
          event.getPlayer().teleport(joinLocation);
        }
```
[Code Source](https://github.com/Shivelight/unexpectedspawn-paper/blob/c04cb69b26d9fe2a324334310b0e3cfe25632f7b/src/main/java/id/shivelight/paper/unexpectedspawn/Spawn.java#L100)

Above code functions based on the following:
1. If the player hasn't played before and on-first-join is true
2. If the config file states that always-on-join is true

So these two are not incompatible together.

**Comment by RexSE7EN** [comment]
I am closing this issue. If anything comes up, do reopen it.
