### ISSUE TITLE
adapt the plugin for Nukkit

### ISSUE THREAD

**Issue by twixi** [DeathGOD7/unexpectedspawn-paper#17]
Is it possible to adapt the plugin for Nukkit?

example: https://github.com/maxxie114/randomSpawn

**Comment by RexSE7EN** [comment]
Nukkit is nuclear-powered server software for Minecraft Bedrock Pocket Edition. It might be written in Java but to make it work in Nukkit, we have to rewrite the code based on their API. And both Spigot/Paper and Nukkit kinda have the same code style but it is best to consider it a separate project.

As for the experience, I have never played any bedrock pocket edition version nor codded plugin for it so I can't test it. Maybe in future, I can try to port this plugin to nukkit if you really need it.

**Comment by twixi** [comment]
this is perfect if you port this plugin to nukkit)

**Comment by RexSE7EN** [comment]
> this is perfect if you port this plugin to nukkit)

Will try to see if I can make simple plugin for nukkit and then port it.

**Comment by RexSE7EN** [comment]
@twixi New repository for Nukkit Port: https://github.com/DeathGOD7/unexpectedspawn-nukkit
(It's not completed and still has some bugs as Nukkit-API is shit)

**Comment by RexSE7EN** [comment]
@twixi Random respawn works nicely when the chunk is pre-generated. As the generation of the chunk is asynchronous and can't work along random respawn properly.

I have added general (kinda bad fix) but the check of blocks will be invalidated if the chunk is not pre-generated.

Also the on-join seems to be broken.

(code updated in new repo)

**Comment by RexSE7EN** [comment]
Closing this issue as a new GitHub repo of the nukkit port is made. Please re-open if you think this issue is not resolved.
