### ISSUE TITLE
Blacklist

### ISSUE THREAD

**Issue by twixi** [DeathGOD7/unexpectedspawn-paper#2]
Please create blacklist in config!  [example:](https://github.com/Josvth/random-spawn/blob/master/src/main/resources/worlds.yml)

**Comment by Shivelight** [comment]
I can't promise, very busy with my study but I will try.

**Comment by twixi** [comment]
im waiting..

**Comment by Roshanxy** [comment]
I’m making it so it blocks lava only, I’ll post it when it works perfect.

**Comment by Roshanxy** [comment]
> 
>         int xmin = plugin.config.getConfig().getInt("x-min");
>         int xmax = plugin.config.getConfig().getInt("x-max");
>         int zmin = plugin.config.getConfig().getInt("z-min");
>         int zmax = plugin.config.getConfig().getInt("z-max");
> 
> 
>         while (true)
>         {
>             int x = xmin + ThreadLocalRandom.current().nextInt((xmax - xmin) + 1);
>             int z = zmin + ThreadLocalRandom.current().nextInt((zmax - zmin) + 1);
>             int y = world.getHighestBlockYAt(x, z) + 1;
>             int b = world.getHighestBlockYAt(x, z);
>         	if((new Location(world, (double) x, (double) b, (double) z).getBlock().getType() != Material.LAVA))
>         	{
>         		return new Location(world, (double) x, (double) y, (double) z);
>         	}
>         } 
>     }

 If you edit the code so it says this and add an import

> import java.util.concurrent.ThreadLocalRandom;

You will never spawn on lava again.
    
Plus, it uses ThreadLocalRandom so the spawn is truly random.
Before, it uses Random, which is seeded, and it would make a new one every time someone joined. You'd always spawn on the same spots before. 

I've added a pull request for it. 
@Shivelight

**Comment by Shivelight** [comment]
@Roshanxy merged, thanks!

**Comment by Roshanxy** [comment]
> @Roshanxy merged, thanks!

I wanna add one more feature where it checks if there is a block on your head because you can sometimes spawn inside lava casts. Should be very simple though

**Comment by Shivelight** [comment]
@Roshanxy Oh, I have work in progress where you can blacklist certain blocks from the configuration. I'll push directly to `master`, so there might be a conflict for you to resolve.

**Comment by Roshanxy** [comment]
It should be quite easy, something with == Material.AIR, perhaps with multiple IF statements

**Comment by twixi** [comment]
1.7.10 not work.... spawning on water =((( KCauldron version 1.7.10-R0.1-SNAPSHOT

**Comment by Shivelight** [comment]
@twixi try adding `STATIONARY_WATER` to the blacklist.

Ref: https://jd.bukkit.org/org/bukkit/Material.html

**Comment by twixi** [comment]
> @twixi try adding `STATIONARY_WATER` to the blacklist.
> 
> Ref: https://jd.bukkit.org/org/bukkit/Material.html

spawn-block-blacklist:
- STATIONARY_LAVA
- LAVA
- STATIONARY_WATER
- WATER

nothing....

**Comment by Shivelight** [comment]
@twixi I'll try to debug it later, though I'm not familiar with KCauldron. I think debugging with Spigot or Paper 1.7.10 should yield the same result?

**Comment by twixi** [comment]
> @twixi I'll try to debug it later, though I'm not familiar with KCauldron. I think debugging with Spigot or Paper 1.7.10 should yield the same result?

I do not know, maybe yes!

**Comment by Shivelight** [comment]
@twixi can you try this?

[unexpectedspawn.zip](https://github.com/Shivelight/unexpectedspawn-paper/files/6364400/unexpectedspawn.zip)

EDIT: Might be related https://www.spigotmc.org/threads/gethighestblockat-returns-air.434090/

**Comment by twixi** [comment]
> @twixi can you try this?
> 
> [unexpectedspawn.zip](https://github.com/Shivelight/unexpectedspawn-paper/files/6364400/unexpectedspawn.zip)
> 
> EDIT: Might be related https://www.spigotmc.org/threads/gethighestblockat-returns-air.434090/

15 "/home" and no water!!!!!! THX!!!!!!!!!!!
