### ISSUE TITLE
Random spawn at  player death

### ISSUE THREAD

**Issue by XlynxX** [DeathGOD7/unexpectedspawn-paper#3]
Please, can u add random spawn at death without beds?
btw very useful and simple plugin

**Comment by Shivelight** [comment]
> Please, can u add random spawn at death without beds?

It does this already, by default. Maybe you mean something else?

**Comment by XlynxX** [comment]
Yeah, sorry for disturbing, i had this problem because of essentials plugin

**Comment by RexSE7EN** [comment]
Closing this issue.
