### ISSUE TITLE
Handle Respawn Anchor

### ISSUE THREAD

**Issue by Shivelight** [DeathGOD7/unexpectedspawn-paper#5]
Ref: https://minecraft.fandom.com/wiki/Respawn_Anchor#History

**Comment by sleepylessons** [comment]
Bump

**Comment by Shivelight** [comment]
@sleepylessons hello, do you have any suggestions on how should the plugin handles the situation? Should it respect the spawn anchor by doing nothing?

**Comment by sleepylessons** [comment]
@Shivelight it should spawn the player at the respawn anchor if they have one, or at their bed if no respawn anchor, or at spawn (randomly) if they have neither. At least for my use case, and SMP server, that makes the most sense. It shouldn't really touch respawn anchor or bed spawns if they are set imo.

Currently respawn anchors are entirely broken by this plugin and therefore it is wholly unusable for me. Willing to donate to this project if we can get a fix, let me know if you need resources to work on this I can potentially get a dev on it.

**Comment by Shivelight** [comment]
Oops, I didn't get your notification. Yeah, ignoring the respawn event if it is an anchor spawn makes the most sense.

**Comment by Shivelight** [comment]
@sleepylessons you can try this 92bf6af

[unexpectedspawn-0.2.0.zip](https://github.com/Shivelight/unexpectedspawn-paper/files/6447953/unexpectedspawn-0.2.0.zip)

**Comment by RexSE7EN** [comment]
Resolved
