### ISSUE TITLE
Worldspawn

### ISSUE THREAD

**Issue by Roshanxy** [DeathGOD7/unexpectedspawn-paper#7]
So from my testing, it seems like players will first use the world spawn before using the plugin.
I'll look into this, but if you fix it before me that's fine too haha

**Comment by RexSE7EN** [comment]
I think there is 'first-join-only' in config file if you want to random tp them when they join the server for first time. 
```
# boolean : only randomize new player spawn.
first-join-only: false
```

**Comment by Roshanxy** [comment]
> I think there is 'first-join-only' in config file if you want to random tp them when they join the server for first time.
> 
> ```
> # boolean : only randomize new player spawn.
> first-join-only: false
> ```

It’s not quite what I meant —
From my observation, people don’t randomly spawn if they join for the first time but do afterwards. I want them to always random spawn if they don’t have a bed. New players spawn on the world spawn first and if they die they spawn randomly. If this world spawn is covered in lava, they die. 

I don’t want them to only random spawn upon joining for the first time, I want them to always spawn randomly unless they have beds. It’s most likely a bug or missing feature.

**Comment by RexSE7EN** [comment]
```
I want them to always random spawn if they don’t have a bed.
```
This is done by the plugin by default.

From what I understand from you is that you want them to be randomly spawned when they first join and also random respawn when they die without a bed or respawn anchor right?

I think it does that both by default. Try enabling that bool in config.

Edit : There is on-join bool in config if you want to random tp when joining even if they had bed. And if you want them to random respawn every time they join and they don't have bed then its not in the plugin yet but you can edit code if you know general programming and rebuild the jar. (it's not that hard.)

**Comment by Roshanxy** [comment]
> ```
> I want them to always random spawn if they don’t have a bed.
> ```
> 
> 
>      
>   
> 
> This is done by the plugin by default.
> 
> 
> From what I understand from you is that you want them to be randomly spawned when they first join and also random respawn when they die without a bed or respawn anchor right?
> 
> 
> I think it does that both by default. Try enabling that bool in config.
> 
> 
> Edit : There is on-join bool in config if you want to random tp when joining even if they had bed. And if you want them to random respawn every time they join and they don't have bed then its not in the plugin yet but you can edit code if you know general programming and rebuild the jar. (it's not that hard.)

If a **new** player joins that has never played on the server before, from my own testing, they spawn at the world spawn. Afterwards, they randomly spawn as intended.

```
@NotNull
Location getSpawnLocation()
Gets the default spawn Location of this world
Returns:
The spawn location of this world
```
^world
which is different from
```
setSpawnLocation
public void setSpawnLocation​(@NotNull
Location location)
Sets player's spawn location.
Parameters:
location - the spawn location
```
and for getSpawnLocation
`Gets player's spawn location. If the player OfflinePlayer.hasPlayedBefore(), it's going to default to the location inside player.dat file. For new players, the default spawn location is spawn of the main Bukkit world.`
^ player

From the java docs.
Setting the respawn location works lovely but I am talking about their first initial spawnpoint which occurs at the world spawn. There are two getspawn / setspawn classes and from reading the code it only sets the player event aka the respawns.

**Comment by RexSE7EN** [comment]
> "For new players, the default spawn location is spawn of the main Bukkit world."

It may be for the default world without any plugins.
```        
        if ((!event.getPlayer().hasPlayedBefore() && plugin.config.getConfig().getBoolean("first-join-only"))
                || plugin.config.getConfig().getBoolean("on-join")) {
            Location joinLocation = getRandomSpawnLocation(joinWorld);
            event.getPlayer().teleport(joinLocation);
        }
```

From what I understand from the above code of this plugin is that if the player hasn't played before and the config has first-join-only bool set to true (or if on-join is set to true) then it gets random spawn location from the user joined world (`getRandomSpawnLocation(joinWorld);`) then it teleports the user to that location.

And for your info the getRandomSpawnLocation function/method is not from bukkit/spigot. Its from here:
```
    private Location getRandomSpawnLocation(World world) {
        int xmin = plugin.config.getConfig().getInt("x-min");
        int xmax = plugin.config.getConfig().getInt("x-max");
        int zmin = plugin.config.getConfig().getInt("z-min");
        int zmax = plugin.config.getConfig().getInt("z-max");
        while (true) {
            int x = xmin + ThreadLocalRandom.current().nextInt((xmax - xmin) + 1);
            int z = zmin + ThreadLocalRandom.current().nextInt((zmax - zmin) + 1);
            int y = world.getHighestBlockYAt(x, z);

            Location location = new Location(world, x, y, z);

            // Special case for server version <1.15.2 (?)
            // Related: https://www.spigotmc.org/threads/gethighestblockat-returns-air.434090/
            if (location.getBlock().getType() == Material.AIR) {
                location = location.subtract(0, 1, 0);
            }

            if (blacklistedMaterial.contains(location.getBlock().getType())) {
                continue;
            }

            return location.add(0.5d, 1d, 0.5d);
```

Code from Source.

**Comment by Roshanxy** [comment]
I've done more tests and it keeps spawning me at or just around the world spawn.
How I've tested it:

Make new server;
Add plugin;
set worldspawn at X0 Z0;
Join server with no player data;
Spawn at world spawn;
Spam lava everywhere at X0 Z0;
Leave server;
Delete player data from the world folder so I am new to the server;
I spawn on lava even though the config says I shouldn't. After dying, it works fine.
Every single time I would spawn at world spawn or near it / around it until everything was filled with lava and it couldn't find a spot without lava. (Repeating it by deleting the player data from the folder so I am new every time)

Every time a new player would join, they'd join onto this lava as it's the world spawn point.

**Comment by Roshanxy** [comment]
I added a debug message for `event.getPlayer().teleport(joinLocation);` but it's not shown when joining fresh but it does for `event.setRespawnLocation(respawnLocation);` after dying

**Comment by RexSE7EN** [comment]
Do you have any other plugins?
Which version did you try? V0.2.1?

> Note: Please don't join before configuring the plugin and by deleting the player.dat file.

Please do this and report back if the problem persists.
1. Do clean new server....install fresh
2. Add plugin
3. Start your server, there should be a config file created.
4. Edit the config file and change first join only to true
5. And restart the server again.
6. Now join the server and see if it randomly teleport you to the new location when joining.

- SE7EN

**Comment by RexSE7EN** [comment]
> I added a debug message for `event.getPlayer().teleport(joinLocation);` but it's not shown when joining fresh but it does for `event.setRespawnLocation(respawnLocation);` after dying

Maybe you haven't enabled first-join-only to true in config.

**Comment by Roshanxy** [comment]
> Do you have any other plugins?
> Which version did you try? V0.2.1?
> 
> > Note: Please don't join before configuring the plugin and deleting the player.dat file.
> 
> Please do this and report back if the problem persists.
> 
> 1. Do clean new server....install fresh
> 2. Add plugin
> 3. Start your server, there should be a config file created.
> 4. Edit the config file and change first join only to true
> 5. And restart the server again.
> 6. Now join the server and see if it randomly teleport you to the new location when joining.
> 
> * SE7EN

The tests I've done was with a fresh server with no plugins and a fresh config.
Enabling first join **only** makes the player randomly respawn and the debug message is shown for _event.getPlayer().teleport(joinLocation);_ but dying will also result in a random respawn ?
So it works but why would it be called first-join-only ? 
Quote from the spigot page:
"Respawn randomly only on new player/first-join." 
Now they respawn randomly when they're new and when they die without a bed -- like it should imo ?

**Comment by RexSE7EN** [comment]
> > Do you have any other plugins?
> > Which version did you try? V0.2.1?
> > > Note: Please don't join before configuring the plugin and deleting the player.dat file.
> > 
> > 
> > Please do this and report back if the problem persists.
> > 
> > 1. Do clean new server....install fresh
> > 2. Add plugin
> > 3. Start your server, there should be a config file created.
> > 4. Edit the config file and change first join only to true
> > 5. And restart the server again.
> > 6. Now join the server and see if it randomly teleport you to the new location when joining.
> > 
> > 
> > * SE7EN
> 
> The tests I've done was with a fresh server with no plugins and a fresh config.
> Enabling first join **only** makes the player randomly respawn and the debug message is shown for _event.getPlayer().teleport(joinLocation);_ but dying will also result in a random respawn ?
> So it works but why would it be called first-join-only ?
> Quote from the spigot page:
> "Respawn randomly only on new player/first-join."

I think there is two event on join and on respawn.
On join checks the first join bool and bool for always random spawn when joining.
And on respawn always respawns when you die. (there is no toggle for it upto current version)

**Comment by RexSE7EN** [comment]
By the way, do you have discord? @Shivelight @Roshanxy ?
If yes please contact me in discord : Death GOD 7#2255
As I am adding features I asked/wanted it to have. And I want to collaborate in this project.

My Repo of this fork : https://github.com/DeathGOD7/unexpectedspawn-paper

**Comment by Roshanxy** [comment]
Mines 만성우울증👽#6568 and my forums https://ursae.roshan.wtf and I love how you're adding your own features and contributing. I have been using this plugin since forever and helped updating it to 1.14 in 2019 and tried fixing some bug (people would randomly spawn in the nether but be stuck inside the floor / ceiling etc it was pretty annoying but he rewrote the whole plugin after) haha It's nice to see fr great work !

**Comment by RexSE7EN** [comment]
> Mines 만성우울증👽#6568 and my forums https://ursae.roshan.wtf and I love how you're adding your own features and contributing. I have been using this plugin since forever and helped updating it to 1.14 in 2019 and tried fixing some bug (people would randomly spawn in the nether but be stuck inside the floor / ceiling etc it was pretty annoying but he rewrote the whole plugin after) haha It's nice to see fr great work !

Ahh, the nether issue... I think the problem was the code he added teleported the user to respawn anchor and the code didn't end there. Which continued to the random tp code.
Random tp code finds the highest block in that world(nether) ``int y = world.getHighestBlockYAt(x, z);`` which is bedrock. And it teleports them. Which was fixed after it was found.

**Comment by Roshanxy** [comment]
> > Mines 만성우울증👽#6568 and my forums https://ursae.roshan.wtf and I love how you're adding your own features and contributing. I have been using this plugin since forever and helped updating it to 1.14 in 2019 and tried fixing some bug (people would randomly spawn in the nether but be stuck inside the floor / ceiling etc it was pretty annoying but he rewrote the whole plugin after) haha It's nice to see fr great work !
> 
> Ahh, the nether issue... I think the problem was the code he added teleported the user to respawn anchor and the code didn't end there. Which continued to the random tp code.
> Random tp code finds the highest block in that world(nether) `int y = world.getHighestBlockYAt(x, z);` which is bedrock. And it teleports them. Which was fixed after it was found.

This bug was a looong time ago though, 2018 or 2019, version 1 
August 2019 I updated it to 1.14 and I wrote
> I haven't fixed a glitch where if you die in the end, you don't spawn on your bed though but you do spawn in the overworld (which before you'd be stuck inside the end or nether) so it's almost perfect

He also wrote to me a month before;

> Sorry for the late response. I lost the source code, and the project itself is just me practicing with the plugin, there are better alternatives that you should try (which I assume you already did). And to be honest I should take this resource down. Thank you!

I'm glad he never took it down but we're getting a bit off topic haha

My problem was solved but it does mean that the first join only is sort of broken I suppose.. Your fork does look very good with the multiple worlds options etc perhaps he could add them to the main plugin.

**Comment by RexSE7EN** [comment]
> My problem was solved but it does mean that the first join only is sort of broken I suppose.. Your fork does look very good with the multiple worlds options etc perhaps he could add them to the main plugin.

Yes, now it does nothing if you are in nether or end. It's fixed.
The only problem now my fork needs to fix is that in a multiverse world(suppose there is x and y and z world)...if they die in y world they respawn in x world. Maybe I need to first declare respawn world in the multiverse plugins world.yml.

If that doesn't help, I would have to add that feature also.

PS : yeah we are going off topic :D

**Comment by Shivelight** [comment]
This is a valid issue. I will check it later after I do my PR review.

Anyway I've been thinking to refactor this project once more to improve the code and expandability, not that I'm going to slap unnecessary pattern, I will keep it simple and easy to read even for someone who started learning. To be honest, since the plugin is small there is not much to refactor, but we'll see.

I do have Discord here Shivelight#7487

**Comment by RexSE7EN** [comment]
> This is a valid issue. I will check it later after I do my PR review.
> 
> Anyway I've been thinking to refactor this project once more to improve the code and expandability, not that I'm going to slap unnecessary pattern, I will keep it simple and easy to read even for someone who started learning. To be honest, since the plugin is small there is not much to refactor, but we'll see.
> 
> I do have Discord here Shivelight#7487

Well, it's fixed in my fork and not that much major issue.
The thing was "first-join-only" misleading name.
But in code it fires in both events on join and on respawn not only first join. So enabling that does both things on death and also on the first join.

**Comment by RexSE7EN** [comment]
Please close this issue if it's solved.
